import Head from "next/head";
import Link from "next/link";
import {
  GoHome,
  GoHomeFill,
  GoSearch,
  GoBookmark,
  GoBookmarkFill,
  GoBook,
} from "react-icons/go";
import { usePathname } from "next/navigation";
import styles from "./index.module.scss";
import { Main } from "next/document";

const MainLayout = ({ children }) => {
  const pathName = usePathname();

  return (
    <>
      <Head>
        <title>Spotify Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://img.icons8.com/ios-filled/50/1DB954/spotify.png"
          alt="spotify"
        />
      </Head>
      <div className={styles.MainLayout}>
        <nav>
          <ul className={styles.navbar}>
            <li>
              {pathName === "/homepage" ? (
                <GoHomeFill className={styles.active} />
              ) : (
                <GoHome className={styles.icon} />
              )}
              <Link
                href="/homepage"
                className={pathName === "/homepage" ? styles.active : ""}
              >
                Home
              </Link>
            </li>
            <li>
              {pathName === "/search" ? (
                <GoSearch className={styles.active} />
              ) : (
                <GoSearch className={styles.icon} />
              )}
              <Link
                href="/search"
                className={pathName === "/search" ? styles.active : ""}
              >
                Cerca
              </Link>
            </li>
            <li>
              {pathName === "/profile" ? (
                <GoBookmarkFill className={styles.active} />
              ) : (
                <GoBookmark className={styles.icon} />
              )}
              <Link
                href="/profile"
                className={pathName === "/profile" ? styles.active : ""}
              >
                La tua libreria
              </Link>
            </li>
          </ul>
        </nav>

        {children}

        <div className={styles.space}></div>
      </div>
    </>
  );
};

export default MainLayout;
